### ISSUE TITLE
Morning partner review

### ISSUE THREAD

**Issue by Nyame-Wolf** [nimplay/Microverse_Portfolio#12]

**Comment by aizjicod** [comment]
hello, nimrod. I am happy to announce that your code can be merged 🎊 🎊 🎊 🎊 🎊 .

- really nice code.
- professional README.

**Comment by Nyame-Wolf** [comment]
The two animations you used were really impressive. They make your portfolio standout. 🥇  I think you can make your portfolio more responsive for mobile by ensuring it covers full view port.
Really nice job overall though. 👏🏾 👏🏾

**Comment by renercrows** [comment]
Very impressive page, but you can make the page for tablets too, as the previous comment, the page is not full width in every display.
